<template>
  <div class="formulate">
    <h2>Formulate!</h2>

    <el-form ref="form" :model="form" label-width="80px">
      <field-builder v-for="(item, index) in formatedSchema" :key="index" :field="item" />

      <hr />

      <!-- <el-form-item label="活动名称">
        <el-input v-model="form.name"></el-input>
      </el-form-item>
      <el-form-item label="活动区域">
        <el-select v-model="form.region" placeholder="请选择活动区域">
          <el-option label="区域一" value="shanghai"></el-option>
          <el-option label="区域二" value="beijing"></el-option>
        </el-select>
      </el-form-item>
      <el-form-item label="即时配送">
        <el-switch v-model="form.delivery"></el-switch>
      </el-form-item>
      <el-form-item label="活动性质">
        <el-checkbox-group v-model="form.type">
          <el-checkbox label="美食/餐厅线上活动" name="type"></el-checkbox>
          <el-checkbox label="地推活动" name="type"></el-checkbox>
          <el-checkbox label="线下主题活动" name="type"></el-checkbox>
          <el-checkbox label="单纯品牌曝光" name="type"></el-checkbox>
        </el-checkbox-group>
      </el-form-item>
      <el-form-item label="特殊资源">
        <el-radio-group v-model="form.resource">
          <el-radio label="线上品牌商赞助"></el-radio>
          <el-radio label="线下场地免费"></el-radio>
        </el-radio-group>
      </el-form-item>
      <el-form-item label="活动形式">
        <el-input type="textarea" v-model="form.desc"></el-input>
      </el-form-item> -->
    </el-form>
  </div>
</template>

<script>
import config from './common/config';
import { parseIntoRealForm, assignForm, formatNormalSchema } from './common/utils';
import { configurableProps } from './common/constant';
import { looseEqual } from './shared';
import FieldBuilder from './fieldBuilder';

export default {
  name: 'Formulate',

  components: {
    FieldBuilder,
  },

  props: {
    value: Object,
    schema: {
      type: Array,
      required: true,
    },
    options: {
      type: Object,
      default: _ => ({}),
    },
    rules: {
      type: Object,
      default: _ => ({}),
    },
    asyncErrors: {
      type: Object,
      default: _ => ({}),
    },
    formProps: {
      type: Object,
      default: _ => ({}),
    },
    useAction: Boolean,
    submitBtnText: {
      type: String,
      default: '确定',
    },
  },

  provide() {
    return {
      form: this.form,
      rules: this.rules,
      options: this.options,
      errors: this.errors,
      getScopedSlots: () => this.$scopedSlots,
    };
  },

  data() {
    return {
      validated: false, // 是否通过校验
      validator: null,

      // generated by props
      formatedSchema: [],
      form: {},
      errors: {},

      config,
      ...configurableProps,
    };
  },

  watch: {
    schema: {
      immediate: true,
      deep: true,
      handler(schema, latestSchema) {
        if (looseEqual(schema, latestSchema)) return;
        this.initSchema();
      },
    },
    value: {
      immediate: true,
      deep: true,
      handler(form) {
        if (looseEqual(form, this.form)) return;
        this.initForm();
      },
    },
    form: {
      deep: true,
      immediate: true,
      handler(form) {
        if (looseEqual(form, this.value)) return;
        this.$emit('input', form);
      },
    },
  },

  methods: {
    initSchema() {
      console.info('%cinit schema', 'color:skyblue;');
      this.formatedSchema = formatNormalSchema(this.schema);
    },
    initForm() {
      console.info('%cinit form', 'color:skyblue;');
      const generatedForm = parseIntoRealForm(this.formatedSchema);
      const mergedForm = assignForm(this.value, generatedForm);
      // set merged formdata
      this.form = mergedForm;
    },

    /**
     * 原生表单校验，对整个表单进行校验的方法
     * @returns {Promise}
     */
    validate() {
      return new Promise((resolve, reject) => {
        this.$refs.form.validate(valid => {
          resolve(valid);
          this.validated = !!valid;
        });
      });
    },

    /**
     * 对部分表单字段进行校验的方法
     * @param {array|string} props
     * @param {Function} callback
     */
    validateField(props, callback) {
      this.$refs.form.validateField(props, callback);
    },

    /**
     * 对整个表单进行重置，将所有字段值重置为初始值并移除校验结果
     */
    resetFields() {
      this.$refs.form.resetFields();
    },

    /**
     * 移除表单项的校验结果
     * @param {string|array} props
     */
    clearValidate(props) {
      this.$refs.form.clearValidate(props);
    },
  },
};
</script>

<style lang="scss" src="./style.scss"></style>
